### ISSUE TITLE
could you give us ability to name files?

### ISSUE THREAD

**Issue by diomed** [nelsonr/super-css-inject#4]
![2023-10-04 07 36 54 pcfpmmmjdgngeidaggcahhoncahmpiin 23425de5fa78](https://github.com/nelsonr/super-css-inject/assets/72777/da04e79c-58f7-48af-b889-ca5dbf82f5a7)

I need to test things, so I upload to cdn file hosting, but it doesnt leave file names, so I often dont know what i'm dealing with. 
could you build in customm name addition perhaps?

**Comment by nelsonr** [comment]
Hi @diomed,

I see how it could be useful. I will consider it for the next release.

Thank you for the suggestion.

**Comment by nelsonr** [comment]
Hi @diomed,

This feature was added on version v1.4.0.

Hope you find it useful.
